### ISSUE TITLE
FilteringSelect with QueryRead.js return strange value

### ISSUE THREAD

**Issue by itdpong** [kfranqueiro/dojo-smore#3] opened 2015-02-16 10:32 UTC
I am trying to replace the dojox.data.QueryReadStore by QueryRead.js in the following example.
http://download.dojotoolkit.org/release-1.10.3/dojo-release-1.10.3/dojox/data/demos/demo_QueryReadStore_FilteringSelect.html

everything works perfect except the returning value once I change to QueryRead.js.
it I search "test" in FilteringSelect, the return value is "test_" in dojox.data.QueryReadStore
but if I change to QueryRead.js, the return value is "/^test._$/im"

would you pls give me some hints, how to solve this???

**Comment by kfranqueiro** [comment] 2015-02-16 20:44
There are a couple of reasons why dropping dojo-smore/QueryRead into that example isn't working.

The first, and the one you are running into with regard to the query string, is due to [some funny business in Dijit](https://github.com/dojo/dijit/blob/1.10.4/form/_SearchMixin.js#L265-L269).

I managed to put together the following workaround that you can try; I'm currently debating whether it belongs in QueryRead itself or whether it might have any adverse effects.

```js
// Assumes your QueryRead store instance is in a variable named `store`
aspect.before(store, 'processQuery', function (query, queryOptions) {
	for (var k in query) {
		query[k] = query[k].toString();
	}
	return [ query, queryOptions ];
});
```

However, you're still going to run into a problem in that the service that that original dojox/data demo page uses returns its results as a comment, not as true JSON.  dojo-smore/QueryRead isn't designed to understand data in this format.  Also, dojo-smore/QueryRead defaults to looking for the total number of results in a `total` property rather than `numRows`, though this can be configured via the `totalProperty` option.

**Comment by vtsuper** [comment] 2015-02-17 05:04
I put your script into my program then everything seems work like dojox.data.QueryReadStore now.
Should I create any ticket in bugs.dojotoolkit.org???

By the way, I found that there are a new module call dstore, is it a replacement of dojo/store???

**Comment by kfranqueiro** [comment] 2015-02-19 04:16
I'm not sure why you would create a ticket on bugs.dojotoolkit.org; there's no bug in Dojo, there are just minor differences between dojox/data/QueryReadStore and dojo-smore/QueryRead.

[dstore](http://dstorejs.io/) is intended as the successor to dojo/store.  It is used by dgrid 0.4.  It has its own RequestMemory store and a Csv store largely adopted from this repository; I don't think it has QueryRead, and I'm not sure whether that's planned for it at this point.

Since it sounds like you got your store working, I'm closing this.  Thanks!

**Closed as completed by kfranqueiro** 2015-02-19 04:16 UTC

**Comment by kfranqueiro** [comment] 2015-02-19 04:17
Sorry, I forgot the context of the stuff that was going on in Dijit.  Unfortunately I'm not sure how likely that is to get "fixed", it is probably working "by design" if I had to guess.  I will poke around a bit and think about adding that workaround to the QueryRead code here though.
